### ISSUE TITLE
Cheat sheet hotkey not working in input fields

### ISSUE THREAD

**Issue by Laban1** [chieffancypants/angular-hotkeys#103]
For data-entry type applications, it would be nice if there were an "AllowIn" setting for the cheat sheet hotkey.  I have redefined the hotkey (cheatSheetHotkey='ctrl+f7'), and it works fine when not in an input field.  

Also, the ability to set preventDefault = true can be very useful to prevent the browser from responding to the key.

I know that I can accomplish the same by binding a hotkey and do toggleCheatSheet manually, but then you have to also create your own template to not include the regular cheat sheet hotkey - it gets a bit messy.

**Comment by fbliss** [comment]
I have the same problem - if an input has the focus, browser defaults take over.

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. This was solved a very long time ago.

**Comment by sibelly** [comment]
How can I set the allowIn property in hotkeysProvider ?
I couldn't found the solution elsewhere.
Thanks.

**Comment by wholeinsoul** [comment]
@Laban1 , @sibelly : were you guys able to make this work ? Thanks.

**Comment by wholeinsoul** [comment]
```
I ended up creating my own cheatsheet hotkey and removed the default key (shift+?) from the menu. The default key still works from non-form elements but is not shown in the menu. 

 .config(function(hotkeysProvider) {
        //hotkeysProvider.cheatSheetHotkey = '?';
        hotkeysProvider.cheatSheetDescription = undefined; // to prevent showing in the menu.
        hotkeysProvider.template = <my template>;
    })
//And in my controller:
 var allowIn = ['INPUT', 'SELECT', 'TEXTAREA'];
  // help menu
  hotkeys.bindTo($scope).add({
                                 combo: 'ctrl+alt+h',
                                 allowIn: allowIn,
                                 description: 'Show/hide this help menu',
                                 callback: function(){
                                     hotkeys.toggleCheatSheet();
                                 },
        });
```
