### ISSUE TITLE
method _add hava bug 

### ISSUE THREAD

**Issue by noiceman** [chieffancypants/angular-hotkeys#107]
in 347 lines of source code
function _add (combo, description, callback, action, allowIn, persistent) {
    ...
     callback = function(event) {
            var shouldExecute = true;
            var target = event.target || event.srcElement; // srcElement is IE only
            var nodeName = target.nodeName.toUpperCase(); 
    ...
}
note:
  if target is 'undefined',then throw TypeError: Cannot read property 'nodeName' of                       undefined。so please add " if(target){.. } " include "var nodeName ..."
For example:
    I want to use Mousetrap.trigger()

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look.  The one you referenced does not exist.
