### ISSUE TITLE
Persistence across routes

### ISSUE THREAD

**Issue by maxbates** [chieffancypants/angular-hotkeys#11]
Hotkeys are persisted when declared in controllers, according to your [comments](https://github.com/chieffancypants/angular-hotkeys/blob/master/src/hotkeys.js#L224) because controllers are persisted, but controllers are re-instantiated by ngRoute... it makes sense to persist hotkeys declared in services, but does it really in controllers? Minimally, could you expose an option on the provider to configure whether hotkeys are persisted by default?

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. This scenario is likely possible using the newer `bindTo` syntax
