### ISSUE TITLE
Hotkey function is bound to the wrong scope when use in routes

### ISSUE THREAD

**Issue by sebastianha** [chieffancypants/angular-hotkeys#110]
When I add a hotkey to a route which calls a function which is using variables depending on the current scope the hotkey works correctly on the first time. But when changing to another route and back the called function is still using the original (old and wrong) scope and not the the new, current one.

I created a small example which shows the problem. When changing to the route the date is saved in a scope-bound variable and is shown in an alert when pressing the hotkey "t". Change to another route and then back. This time the hotkey still calls the same old function with the same old date even if the variable of the current scope has been updated.

For me it seems that there the wrong scope is used by the hotkey. This is causing very strange and unpredictable behavior and should be fixed. I tried to figure it out where the problem is but had not enough time yet. Perhaps you have an idea what could be wrong.

Using the example:
 - First unzip it and run "bower install" to install missing dependencies
 - Start a webserver in the directory ("python -m SimpleHTTPServer 8000") or upload it somewhere
 - Open the index page and press "t". Now you see the current date which has been generated when the current page has been initialized (also in the console).
 - Change the route by clicking on "test2"
 - Change it back by clicking on "test1"
 - Press the hotkey "t" again and you will see the same date as before, not the one of the current scope.

You find the example here: http://omoco.de/hotkeys_bug.zip

**Comment by davinkevin** [comment]
+1, seems to have same problem with my app https://github.com/davinkevin/Podcast-Server 
That leads to strange behavior like keypress in input inside directive to fire event even if I don't use AllowIn.

**Comment by sebastianha** [comment]
Could you test my fix #113 if this works for you?

**Comment by RomFouq** [comment]
I have the same problem. Please fix it, it's really annoying and makes your library, that's otherwise really great :tada:, unusable for me...

**Comment by sebastianha** [comment]
I have fixed the bug in my fork here: https://github.com/sebastianha/angular-hotkeys/tree/bugfix-wrong-scope

**Comment by RomFouq** [comment]
I've seen your PR but I didn't take the time to test it, perhaps @chieffancypants waits for tests to merge this.

**Comment by mkw1** [comment]
Thanks @sebastianha...your fix helped me out.

**Comment by sebastianha** [comment]
@chieffancypants Did you take a look at the pull request #113 ?
Can you reproduce the problem?

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look.

**Comment by sebastianha** [comment]
See here: http://plnkr.co/edit/ZN4HaJifqS02s8nU4FZC

**Comment by sebastianha** [comment]
For me this bug is still present, could you please take a look at it?

Updated Plunker: http://plnkr.co/edit/ZVLpf3EIk0Aa97IAJBDF
