### ISSUE TITLE
Combos of characters (without ctrl or alt) activate on last character in combo.

### ISSUE THREAD

**Issue by RobiFerentz** [chieffancypants/angular-hotkeys#112]
So I'm integrating this module into our app. My boss has some weird ass combo requirements.
So 'g+c' is supposed to navigate to a certain page. It works great. However, it also works if I just press 'c' alone without 'g'.

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. I don't think this is possible,  Combination keys can only be used with modifiers CTRL, CMD, SHIFT, etc.  You're better off using sequences for those stranger ones.
