### ISSUE TITLE
Doesn't work when using non-standard start/end symbols

### ISSUE THREAD

**Issue by rpungello** [chieffancypants/angular-hotkeys#115]
Since the template is hard-coded to use {{ and }} for the AngularJS start/end symbols, if the parent app is configured to use something else, this plugin doesn't work (see below).

It's simple enough to fix by replacing the {{ and }} in hotkeys.js with the new symbols (which I'm currently doing automatically via Grunt), but if it could be handled natively that'd be nice.

```
app.config([
	'$interpolateProvider',
	function ($interpolateProvider)
	{
		$interpolateProvider.startSymbol('<%');
		$interpolateProvider.endSymbol('%>');
	}
]);
```

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If this is still important to you, please open a PR. Thanks!

**Comment by Mathem8tic** [comment]
I am also having the issue outlined above.  Using Laravel has prompted me to change the $interpolateProvider to something that does not conflict with the blade syntax.  It would be nice to have this feature accept the current values of the startSymbol and endSymbol.
