### ISSUE TITLE
Bind to scope doesnt work properly

### ISSUE THREAD

**Issue by Duskfall** [chieffancypants/angular-hotkeys#117]
I have 3 controllers
<div ng-controller="parent>
     <div ng-controller="child1"></div>
     <div ng-controller="child2">(hotkeys here)</div>

</div>

But when i try to press a key that is binded in child2 and i am inside child1 it calls the function declared in child2.
Shouldn't these be isolated?

// Controller child2
         hotkeys.bindTo($scope)
                .add({
                    combo: "enter",
                    description: "test",
                    allowIn: ['INPUT', 'TEXTAREA'],
                    callback: function (event, hotkey) {
                        event.preventDefault();
                        callFunction();
                    }
                });

**Comment by sjahreis** [comment]
+ 1

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. 

I assume that when you say that you're "inside child1" you are suggesting that an element in child1 has focus, correct?  Hotkeys are global, so this isn't possible.  Scope binding is simply to allow those hotkeys to exist only as long as that scope exists.
