### ISSUE TITLE
Remove need to add "hotkey-allow-in" if hotkey directive is used on an <input> element

### ISSUE THREAD

**Issue by NicBright** [chieffancypants/angular-hotkeys#119]
Say I would like to add a hotkey directly on an `input` element. Right now, I would have to additionally add `hotkey-allow-in="input"`. I see room for an improvement here: the directive should check whether it is applied onto an `input` element and then add the hotkey-allow-in attribute automatically.

The same should be true for the other types of elements: `textarea` and `select`.

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If this is still important to you, please open a PR.  Thanks!
