### ISSUE TITLE
Hotkey grouping

### ISSUE THREAD

**Issue by javiermarinros** [chieffancypants/angular-hotkeys#120]
It would be nice to group hotkeys by section or functionality, something like this:

![angularhotkeys js keyboard shortcuts for your angular apps](https://cloud.githubusercontent.com/assets/840412/5501918/83875412-8762-11e4-929d-7504db35cad6.png)

**Comment by Antariano** [comment]
+1

**Comment by dan-silver** [comment]
+1

**Comment by silverprize** [comment]
+1
or I hope hotkey service provide to swap keyset.

**Comment by kfei** [comment]
+

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If this is important to you guys, please open a PR for it.  Thanks!

**Comment by gastonelhordoy** [comment]
Hey @chieffancypants, any chance you could merge #205 any time soon? Thanks for this great module!
