### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [chieffancypants/angular-hotkeys#122]
Hi @chieffancypants,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme?

This is the page we provide cdn for angular-hotkeys - https://cdnjs.com/libraries/angular-hotkeys

Thanks!

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. Happy to take a PR on it -- but I imagine these smaller projects are usually concatenated into a single file instead of relying on a CDN in the way you might when linking to angular or bootstrap.

**Comment by PeterDaveHello** [comment]
Okay, it's up to you!
