### ISSUE TITLE
Arrow direction in form fields

### ISSUE THREAD

**Issue by davinkevin** [chieffancypants/angular-hotkeys#129]
Hi, 

I have a problem with the angular-hotkeys plug-in.

I defined on a route a keyboard shortcut for right and left arrow. ( https://github.com/davinkevin/Podcast-Server/blob/master/src/main/webapp/app/js/modules/search/search.item.js )
But if I use this same arrow in an input field (or others text fields) it calls the action defined in the route.

In the Angular-Hotekys docs, you explain we have to use the allowIn parameters to allow mousetrap event in text fieds... but it seems the arrow trigger the event even if allowIn is not defined.

Thanks

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets.  If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look

**Comment by davinkevin** [comment]
Example in Angular-Hotkeys 1.4.5 : http://plnkr.co/edit/Znu42vEq9A6QTR2s4UQ9?p=preview

Seems to be fixed in 1.6.0, will update and see if everything works on my project

**Comment by davinkevin** [comment]
In both plunker, I use left and right key to add or remove 1 of the controller value. 

The recent 1.6.0 not working at all with hotkeys in ngRoute : http://plnkr.co/edit/Znu42vEq9A6QTR2s4UQ9

With the latest version I use (1.4.5 - same code) I have reproduce the bug in the following plunker : http://plnkr.co/edit/JTFlfDHfz0ePB4tfOWQ6?p=preview

Thanks for your help

**Comment by davinkevin** [comment]
Could you re-open this ticket ? 

Thanks

**Comment by davinkevin** [comment]
@chieffancypants, closing ticket and asking for a plnkr and not re-opening or answering when people give you the example... it's sad :cry:
