### ISSUE TITLE
Disabling cheat sheet conditionally

### ISSUE THREAD

**Issue by kandadaboggu** [chieffancypants/angular-hotkeys#131]
I want to disable the cheat sheet on public pages and show them on authenticated pages. 

When I set `includeCheatSheet` in a `run` block or in a controller the cheat sheet is still shown.
```
App.run(['hotkeys', 'AuthUser', function(hotkeys, AuthUser) {
  if (AuthUser.authenticated) {
    // add hot keys
  }
  else {
    // the cheat sheet is already added to the DOM. the line
    // below has no impact
    hotkeys.includeCheatSheet = false;
  }
}])
```

I rely on an authentication service to detect if a user is authenticated. This service is not available in the config block. 

```
App.config(['hotkeys', function(hotkeys) {
  // can't access the AuthUser service 
}]);
```

How do I disable cheat sheet in a `controller` or in a `run` block?

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets.  This would likely require a lot of reworking to get it going, but a simple work around could be to remove the `?` hotkey that is added automatically, and re-add it after authenticating.
