### ISSUE TITLE
ctrl++ is not working

### ISSUE THREAD

**Issue by EladBezalel** [chieffancypants/angular-hotkeys#135]
Im trying to use ctrl and + in the same time and its not working..
ctrl+- works but ctrl++ doesn't work..

**Comment by chino23** [comment]
I think it's a mousetrap thing. It was just updated to 1.5.x where it says it improved the handling of the + key. Let's see what the answer for https://github.com/chieffancypants/angular-hotkeys/issues/139 is

**Comment by RomFouq** [comment]
It's just an idea, but maybe the problem comes from this line:
https://github.com/chieffancypants/angular-hotkeys/blob/master/src/hotkeys.js#L104

**Comment by EladBezalel** [comment]
@RomFouq yup.. i think your'e right..

**Comment by RomFouq** [comment]
After looking closer at the code, I think this is not the problem... This function `symbolize` seems to be called only to `format` the string, for the cheat-sheet, at line:
https://github.com/chieffancypants/angular-hotkeys/blob/master/src/hotkeys.js#L53.

**Comment by chieffancypants** [comment]
This should be handled by the latest mousetrap
