### ISSUE TITLE
Recommended approach to capture when 'esc' is pressed when an input has focus

### ISSUE THREAD

**Issue by sstorie** [chieffancypants/angular-hotkeys#136]
I am trying to add a hotkey within a directive for when a user presses escape while an input field has focus. When the input field has focus the 'esc' press never triggers my hotkey callback, but if I click outside of the input (so it no longer has focus), then my callback is called. Is there a recommended approach for this?

My use case is I'm using '/' to set focus on a global search input, and want to bind 'esc' to blur the field if the user decides they don't want to search any longer. I also have some visual changes that happen in this transition.

**Comment by vyegres** [comment]
use "allowIn" property -  https://github.com/chieffancypants/angular-hotkeys/#hotkeysaddobject

example:
        hotkeys.bindTo($scope).add({
            combo: 'ctrl+enter',
            allowIn: ['INPUT', 'SELECT', 'TEXTAREA'],
            callback: function(event, hotkey) {
                event.preventDefault();
                $scope.save();
            }
        });

**Comment by sstorie** [comment]
This is exactly what I was looking for, and of course it's clearly in the docs now that I know what to look for. Thanks for replying!
