### ISSUE TITLE
Alt+0 from numpad doesn't work

### ISSUE THREAD

**Issue by roman-yerin** [chieffancypants/angular-hotkeys#137]
Alt+(0 from numpad) doesn't work. 0 from the upper keyboard row works fine.

**Comment by chieffancypants** [comment]
This is likely because alt+numpad has special meeting as it allows you to create a sequence of unicode characters.  If this works in the mousetrap library, and doesn't here, then it's an issue, and we can reopen

**Comment by nataliaw** [comment]
It is fixed in mousetrap library in version 1.6.1
