### ISSUE TITLE
repo dead?

### ISSUE THREAD

**Issue by diego-vieira** [chieffancypants/angular-hotkeys#138]
Hello @chieffancypants 1k+ people loves your work and it would be a shame to let it die.
It seems that the last commit was back in October/2014 and a lot of issues raised and PRs are waiting to be merged.

I would be glad to help as a maintainer.
Thanks

**Comment by chieffancypants** [comment]
Sure, I could use the help.  Right now the biggest issue with the PRs tend to be feature bloat.  Everyone wants something added, but the use-case is generally extremely specific meaning 99% of developers will not use the feature.  I'd prefer not to have a gigantic library, and keep this short and sweet.

If you agree with the general philosophy, and would like to help maintain and solve bugs while implementing a few key features here and there, I'd definitely appreciate the help

**Comment by diego-vieira** [comment]
Ah awesome, in that case I'll try to help with the issues then.
cheers!
