### ISSUE TITLE
Please expose hotkeys array

### ISSUE THREAD

**Issue by Hypercubed** [chieffancypants/angular-hotkeys#144]
I am creating my own hotkeys help menu.  To do this I need to expose the `scope.hotkeys` array through the `hotkeys` service.  I am willing to submit a PR.

**Comment by mprokopowicz** [comment]
+1

**Comment by mprokopowicz** [comment]
@chieffancypants This one is probably closed by 52a76490f2a6aeb83d11ee59431a2e1ab6bc4e05

**Comment by chieffancypants** [comment]
This has been solved a while back
