### ISSUE TITLE
Can a hotkey simulate a click ?

### ISSUE THREAD

**Issue by kktos** [chieffancypants/angular-hotkeys#148]
Most of the time (in our applications, at least) we have buttons with kbd shortcuts.
The action is defined into the ng-click directive. So we need to duplicate it for the hotkey.
I would be nice to be able to use the expression set in ng-click as action for the hotkey.
So in other words, a way could be to simulate a click with a hotkey.

thx
kktos

**Comment by chieffancypants** [comment]
You should just point the hotkey callback to the same method executed by the ng-click

```js

$scope.functionUsedByNgClick = function () {
 // ...
}

hotkeys.add({
  combo: 'w e s'.
  callback: $scope.functionUsedByNgClick
});
```
