### ISSUE TITLE
function key F1,F2, etc. not working with hotkeys ?

### ISSUE THREAD

**Issue by njarasoa** [chieffancypants/angular-hotkeys#151]
Hi, 

I'm trying to map these keys with some function but I can't. Does anyone already face this problem ?
Do you have solution? Thank you,

This is my code
        hotkeys.add({
                combo: 'F2',
                description: '',
                callback: function(event) {
                    alert("F2 key") ;
                    event.preventDefault() ;
                }
            })

**Comment by garethhunt** [comment]
Try using a lower case 'f'.  I just tested add f2 worked, while F2 did not.

**Comment by chieffancypants** [comment]
Cool, closing as it seems to be resolved, thanks @garethhunt

**Comment by lmichailian** [comment]
Comment: If is Mac or Laptop you maybe need example: fn+f1
