### ISSUE TITLE
Chrome browser issue related with using specific keyboard shortcuts

### ISSUE THREAD

**Issue by Uma19** [chieffancypants/angular-hotkeys#157]
Hi guys,

First of all really nice implementation :).
I found one issue regarding using this hotkeys on chrome browser.
The below key combination is not working properly on Chrome browser ("Version 43.0.2357.124") and executing the default's behavior. and surprising it works on IE 9 11 :)
ctrl+n
Ctrl+t
ctrl+ w

When I tried to debug the code then there is a function called "_handleKeyEvent" which is not capturing the key combination which I had mentioned above.

So can you help me out with this issue?

**Comment by chieffancypants** [comment]
This is not something you can override: https://github.com/ccampbell/mousetrap/issues/172

Additionally, you wouldn't want to even if you could.  Overriding standard shortcuts would be incredibly annoying to your end users when they suddenly can't open new browser windows or tabs.
