### ISSUE TITLE
To use the shift+? from executing another function

### ISSUE THREAD

**Issue by Uma19** [chieffancypants/angular-hotkeys#158]
Hi Guys,
I want to use shift+? for executing my external functionality. but its by default opens your help menu.
How can I avoid to open the default help menu which you provide? 
I tried to disable the cheatsheet setting but still its not working.

Please guide me for the above issue
Thanks in advance

**Comment by chieffancypants** [comment]
I don't think there's an explicit test case for this, so it's possible that it's not working.  Can you create a fiddler or something so I can ensure everything is configured correctly?

**Comment by Uma19** [comment]
Thanks for your response chieff.
Will create one sample and sent it over to you. right now for solving my purpose I have used some other character to open my help menu
