### ISSUE TITLE
Problem with bower.json

### ISSUE THREAD

**Issue by probablycorey** [chieffancypants/angular-hotkeys#16]
It looks like there are two angular-hotkeys packages in bower [angular-hotkeys](https://github.com/drahak/angular-hotkeys) and [chieffancypants/angular-hotkeys](https://github.com/chieffancypants/angular-hotkeys). `chieffancypants/angular-hotkeys` is the package I want because it is up-to-date.

But in my bower.json this line:

``` json
"dependencies": {
  "chieffancypants/angular-hotkeys": "~1.1.0",
}
```

causes the error `bower ENOTFOUND     Package chieffancypants/angular-hotkeys=chieffancypants/angular-hotkeys not found`

If I change my dependency to this:

``` json
"dependencies": {
  "angular-hotkeys": "~1.1.0",
}
```

It will fail because the bower only has angular-hotkeys@0.2.1.

I'm new bower and angular so this might be entirely my problem, but my guess is that the un-namespaced `angular-hotkeys` needs to be unpublished from bower?

**Comment by Chklang** [comment]
Can you update your README.md with the command `bower install chieffancypants/angular-hotkeys --save` ?
