### ISSUE TITLE
allow to provide a separate key combo for documentation

### ISSUE THREAD

**Issue by ittayd** [chieffancypants/angular-hotkeys#160]
it seems that for modifier+key combinations, the event triggers with the english key, even if the layout is in another language (at least for me, using english+hebrew layouts). this seems inherent in javascript. while the best solution is for the framework to map the non english characters to their english equivalent when handling key presses, it seems this is tricky (if possible). an alternative is to just allow to pass a key combination that will be used in the documentation. so while binding to alt+t, the documentation will show alt+א

**Comment by chieffancypants** [comment]
I'm not in control of this, as all hotkey-specific binding is handled by mousetrap.  You may want to open a ticket there

**Comment by ittayd** [comment]
I was suggesting that an optional parameter will be allowed and that will be used for documentation. So I call with both alt+t and alt+א, you pass alt+t to mousetrap and show alt+א in the documentation ('?')
