### ISSUE TITLE
Modify associated DOM element to event

### ISSUE THREAD

**Issue by xsenechal** [chieffancypants/angular-hotkeys#162]
I have several inputs and when type a hotkey inside one of them, I would like the hotkey callback to edit the content of the input. uses cases are uppercase, leftpadd...

I have created a fiddle where I can update the input value but the change is not reflected in the angular model:
http://jsfiddle.net/xsenechal/xLo5vtL6/5/
A $scope.$apply does not work in this place.

Is is feature easily provided by the plugin ?

**Comment by chieffancypants** [comment]
Hmm, that's a pretty specific use-case, I'm not sure how I would incorporate generically into this library.  It's probably better off handled in your own app logic.
