### ISSUE TITLE
controllerAs support

### ISSUE THREAD

**Issue by jmls** [chieffancypants/angular-hotkeys#163]
I want to be able to  bind it to the controller's scope, but i am using the controlleras syntax and not passing $scope into the controller.

Is there a way to bind to the controller scope using controlleras ?

thanks

**Comment by chieffancypants** [comment]
Are you opposed to injecting $scope into the controller for some reason?  It's still necessary for setting up things like `$watch`, so that would be my recommendation.

**Comment by ryanfinken** [comment]
I don't mind using $scope if necessary, but I would be interested in a way to bind without using $scope as well. I have removed the need for $scope in the vast majority of my application's controllers and would rather not have to add it back in.

Thanks!
