### ISSUE TITLE
cmd + s

### ISSUE THREAD

**Issue by oisinlavery** [chieffancypants/angular-hotkeys#164]
I want to override the browser default and use cmd + s to save a version in my web app.

Is this possible using angular-hotkeys?

**Comment by oisinlavery** [comment]
Ok I got this working almost instantly after I posted...

- use mod instead of cmd
- use preventDefault on the callback event

```
hotkeys.bindTo($scope).add({
  combo: "mod+s",
  callback: function(e) {
    e.preventDefault();
    save();
  }
});
```

**Comment by BrandonCopley** [comment]
Why is this the case? I'm doing the same thing in my app and curious because ctrl+s is saving, but I'm on a mac, so I want it to be command+s, but for PC I want it to be ctrl does mod solve that?

**Comment by theclapp** [comment]
Yes, mod solves that.  mod is a feature of Mousetrap, and on a Mac maps to Command, but on Windows & Linux maps to Control.  See https://craig.is/killing/mice.
