### ISSUE TITLE
Plus sign not supported in combo keys

### ISSUE THREAD

**Issue by bagaliu** [chieffancypants/angular-hotkeys#167]
I want to implement "ctrl+plus" in my controller, but it doesn't work. Looks like Mousetrap is supporting it.

**Comment by lior-erez** [comment]
Try combo: 'ctrl+='
That should resolve the issue

**Comment by chieffancypants** [comment]
The latest hotkeys should have the updated Mousetrap, so this issue should be solved

**Comment by jonathan-reisdorf** [comment]
Mousetrap only partially supports it (on numpad, not as "normal" key), but still you are right, this issue is not an angular-hotkeys specific issue.
