### ISSUE TITLE
Unable to display cheat sheet

### ISSUE THREAD

**Issue by bithive** [chieffancypants/angular-hotkeys#168]
The hotkeys I've defined are working, but `?` fails to open the cheat sheet.  I've tried calling `hotkeys.toggleHelp()` as in the example and `hotkeys.toggleCheatSheet()`, to no avail.

**Comment by chieffancypants** [comment]
Not sure how to help you without a reduced test case.  If you can reproduce on a plunkr/jsfiddle please reopen the issue.
