### ISSUE TITLE
Expose key mappings

### ISSUE THREAD

**Issue by tomgutz** [chieffancypants/angular-hotkeys#176]
Right now the key mappings are declared privately. Our requirement is have the "shift" key to show as textual rather than the shift symbol. I suggest that we expose the key mapping or maybe a API to replace the default one or maybe introduce new ones. I can provide code if necessary.

**Comment by bimovidia** [comment]
+1 on this

**Comment by chieffancypants** [comment]
Happy to review a PR if you can manage a very simple way to accomplish this.  Closing this issue in favor of a future PR.
