### ISSUE TITLE
not working right after bootstrap

### ISSUE THREAD

**Issue by yoorek** [chieffancypants/angular-hotkeys#177]
hotkeys are not active right after bootstrapping (refreshing appplication) - i have to click anywhere and then it works.
I tried to focus non-input element, force click - nothing works.
Is it possible bug or my fault (I notice that your demo works)

**Comment by chieffancypants** [comment]
This is likely not an issue with hotkeys, but if you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look
