### ISSUE TITLE
Delay creation of DOM element 

### ISSUE THREAD

**Issue by scottfwalter** [chieffancypants/angular-hotkeys#178]
I need the ability to set cheatSheetDescription after initialization primary because I need to localize the message.  Would be nice to see if there was a way to either delay the creation of the dom or provide a way to refresh the template.  I have access to the cheatSheetDescription however setting it has not effect.

--Scott.

**Comment by chieffancypants** [comment]
I think this makes sense.  I'm willing to review a PR if this is important to you, but I won't have the time to work on it myself, unfortunately :(

**Comment by scottfwalter** [comment]
Cool.  I'll probably need this for my project as it requires internationalization support.  I'll submit a PR when I work on this.  Probably in a week or two.
