### ISSUE TITLE
How to intercept the "Enter" key?

### ISSUE THREAD

**Issue by sonnyk22** [chieffancypants/angular-hotkeys#180]
Using the below code I am intercepting the "=" key.  How to intercept the "Enter" key using this library using the code below (or something similar)?

                hotkeys.bindTo($scope).add({
                    combo: ['='],
                    description: "=",
                    callback: function (event, hotkey) {
                        event.preventDefault();

                        // do something code here
                    }
                });

**Comment by chieffancypants** [comment]
use the word `enter` instead of `=`

**Comment by sonnyk22** [comment]
I am already using the "=" key, but the requirement at my work is asking for the Enter key.  Is there a possibility to achieve this request using the HotKey lib? I hope so.
