### ISSUE TITLE
can't assign hotkey when input in focused

### ISSUE THREAD

**Issue by btm1** [chieffancypants/angular-hotkeys#187]
if i have an input focused I can't seem to get any hotkeys to work ... so this is based on focus? Also if i unfocus an input that was selected with js and i don't focus the document or the body again using js than these keybindings don't work either.

**Comment by alcance** [comment]
Same issue here. Did you find any workaround ?

**Comment by alcance** [comment]
Found the fix. This is moustrap library by default.

https://craig.is/killing/mice/#api.bind.text-fields

Just add class="mousetrap" to your input. Greetings.

**Comment by alazzawimahmoud** [comment]
You need to add allowIn property : 
      hotkeys.add({
        combo: 'ctrl+y',
        description: 'Tasks',
        allowIn: ['INPUT', 'SELECT', 'TEXTAREA'],
        callback: function(event, hotkey) {
        }
      })

**Comment by chieffancypants** [comment]
@alazzawimahmoud thanks for the help.  This is correct.
