### ISSUE TITLE
 Mouse Click/Scroll + Key Combinations

### ISSUE THREAD

**Issue by devonzara** [chieffancypants/angular-hotkeys#188]
I'm working on an application where key combinations along with mouse click/scroll events are used as hotkeys, is there a way to define these type of combinations in angular-hotkeys?

**Comment by theclapp** [comment]
That sounds kind of neat.  Can you give an example?

**Comment by devonzara** [comment]
Sure, the use-case I'm working on is a drawing application where simply scrolling could be configured to zoom and pressing Ctrl while scrolling could, perhaps, adjust the brush size.

However, since making this post, I realize now that this is a limitation of the Mousetrap library. I guess adding mouse events to that would be the first step in gaining support for them here. 

Now that I think about it though, implementing that would then raise issues on rather or not support for [PointerEvents](http://www.w3.org/TR/pointerevents/) should be implemented too since it's already supported by IE and is being worked on by Firefox and Chrome as well.
