### ISSUE TITLE
Cheatsheet close icon

### ISSUE THREAD

**Issue by DrogoNevets** [chieffancypants/angular-hotkeys#192]
![cheatsheet](https://cloud.githubusercontent.com/assets/1665375/10788114/299f6618-7d6d-11e5-8b85-3e7b5af00c8c.png)

The close icon for cheatsheet appears wrong....is there a fonts file I am missing?

**Comment by rinu** [comment]
It's a web server issue, nothing worng with this project.
On my wamp server I had absolutely no Content-Type header in the response, so I added the following to my .htaccess:
AddType 'application/javascript; charset=UTF-8' js

**Comment by DrogoNevets** [comment]
AH brilliant, will give that a go, thank you!

**Comment by DrogoNevets** [comment]
Worked perfectly thank you!
