### ISSUE TITLE
Custom Cheatsheet hotkey not working while in form element

### ISSUE THREAD

**Issue by MrTarantula** [chieffancypants/angular-hotkeys#196]
I want to be able to trigger the cheatsheet while in a form, so I set

> hotkeysProvider.cheatSheetHotkey = 'alt+q'

but while I'm in an input field, the cheatsheet will not open.

**Comment by wholeinsoul** [comment]
@MrTarantula : were you able to make this work ?

**Comment by MrTarantula** [comment]
This issue is 4 years old. I don't even remember the last time I used Angular 1.
