### ISSUE TITLE
Disable hotkeys temporarly

### ISSUE THREAD

**Issue by hiramegl** [chieffancypants/angular-hotkeys#202]
I would like to disable hotkeys temporarly, for instance when I open a modal window or when I have implemented keyhandlers in some forms.

Right now I introduced a variable "hotkeysEnabled" in $rootScope which i check before executing wrapApply.

Thanks for your help in advance.

**Comment by chieffancypants** [comment]
I don't think there's an easy way to do that now, but the use-case seems solid, so I'm open to a PR, but unlikely to add this myself.  Thanks!

**Comment by chieffancypants** [comment]
Looks like there's a PR for this already.  I'll bring it up-to-date and merge in
