### ISSUE TITLE
angular-hotkeys for Angular 2?

### ISSUE THREAD

**Issue by sebhildebrandt** [chieffancypants/angular-hotkeys#215]
Hi, first of all: GREAT component, thank you for your work. 
My question: du you have plans to implement a angular 2 version? I know, this will require more or less a complete rewrite ... but still I am interested to know. Otherwise I guess I need to dig into writing a small alternative (which will definitely not be that fancy!!!!) ;-)
Regards

**Comment by chieffancypants** [comment]
No plans yet.  I don't have enough real-world experience with angular2 to write something that I would feel confident about deploying into production.  Will likely happen at some point though.

The real question is whether that becomes a separate repo, or a new branch that eventually becomes master.  Have you seen any other components making this transition?

**Comment by brtnshrdr** [comment]
I have started a rewrite for angular 2 here: https://github.com/brtnshrdr/angular2-hotkeys
Feel free to check it out and report any bugs or submit any pull requests!

**Comment by k11k2** [comment]
@chieffancypants  is there any plan to support angular 2 ? much needed one.

**Comment by brtnshrdr** [comment]
@AlwaysAbhl001 I've created an Angular 2 version, similar to this project. It's available here:
https://github.com/brtnshrdr/angular2-hotkeys

**Comment by k11k2** [comment]
@brtnshrdr  could you provide perfect example for this.

and could pls you guide regarding this issue.
TypeError: core_1.InjectionToken is not a constructor

exports.HotkeyOptions = new core_1.InjectionToken('HotkeyOptions'); -- library File

For more info: TS2305: Module '"~/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.



![image](https://cloud.githubusercontent.com/assets/26591838/25391672/6872998e-29f4-11e7-8f57-fe20ce1ac524.png)

![image](https://cloud.githubusercontent.com/assets/26591838/25391714/7db2e9a2-29f4-11e7-94f1-c2dcf84756f0.png)
