### ISSUE TITLE
Using $translate and $templateCache

### ISSUE THREAD

**Issue by Zomono** [chieffancypants/angular-hotkeys#246]
The settings for internationalized strings and cheat-sheet-template have to be made within the config-phase of angular. This is a problem because $translate and $templateCache are not ready to use at this time.
Thus it would be nice 
- to accept a language-key instead, which will be translated later by $translate
- to accept a template-url which will be used to fetch the template later

Thanks in advanced

**Comment by felipeplets** [comment]
@Zomono this is exactly what I'm looking for. Be able to use $translate in the hotkeys cheatsheet. Are there any current workarounds to make it work?

**Comment by Zomono** [comment]
I don't know the current state of this project. Maybe something has been implemented in the meanwhile.
Has a dirty workaround you may load and access the translation data the same way you do to initialize $translate.
