### ISSUE TITLE
Support for F*

### ISSUE THREAD

**Issue by fabdelgado** [chieffancypants/angular-hotkeys#256]
Hi, this library support keys as F5 r F6,F11?
How to implement this use?

**Comment by gondik** [comment]
Hi, this works for me normally:

```
hotkeys.add('f5', 'Example for F5 key', function (event) {
  event.preventDefault();
  console.log('You pressed F5 key');
});
```

**Comment by ronssij** [comment]
Hi, 'ctrl+f5' ?
how is this not working?

**Comment by aramando** [comment]
@ronssij I have no problem using 'ctrl+f5'. Are you sure you are cancelling the default action of the event in the callback (as in gondik's example above)? Because of course Ctrl+F5 hard-refreshes the page by default, so maybe it is working but is then immediately reloading your app.
