### ISSUE TITLE
Programmatically open hotkeys dialog

### ISSUE THREAD

**Issue by antjori** [chieffancypants/angular-hotkeys#269]
Hey @chieffancypants,

Thank you for this awesome feature! :smiley:

Is it possible to open the hotkeys dialog programmatically? If so, is it possible to provide a way to accomplish it?

Thanks.

**Comment by aramando** [comment]
`hotkeys.toggleCheatSheet()` :-)

(see https://github.com/chieffancypants/angular-hotkeys/blob/master/src/hotkeys.js#L580)

**Comment by antjori** [comment]
Thank you so much @aramando :+1: 

I'll give it a try!!
