### ISSUE TITLE
hotkey with mod+w closes the browser tab

### ISSUE THREAD

**Issue by bobharley** [chieffancypants/angular-hotkeys#282]
It closes the browser tab even with `e.preventDefault()` and/or `e.stopPropagation()`
Is there a way to override this behavior?

``` javascript
hotkeys.add({
  combo: 'mod+w',
  description: 'Close tab',
  allowIn: ['INPUT', 'SELECT', 'TEXTAREA'],
  callback: (e, hotkey) => {
    e.preventDefault()
    e.stopPropagation()
    // code here
  }
})
```

**Comment by aramando** [comment]
No. Browsers don't let you prevent users from closing tabs, windows or the browser application itself using keyboard shortcuts for security and usability reasons.
