### ISSUE TITLE
Package not found in bower

### ISSUE THREAD

**Issue by Martinspire** [chieffancypants/angular-hotkeys#82]
Apparently there are two angular-hotkeys packages in bower. The one from drahak and this one. This is found in chieffancypants/angular-hotkeys and the other is angular-hotkeys. Unfortunately (i cannot seem to find why) this one cannot be used in bower because it will get the other package or throws an ENOTFOUND error (even though it resolved and downloaded it).

Anybody got a solution for me or is this package gonna need some renaming to get it better in bower?

Edit:
Got it working with this:

``` js
"angular-hotkeys": "chieffancypants/angular-hotkeys#1.4.3"
```

But that seems like a temporary fix rather than a solution

**Comment by renato** [comment]
I know this issue is closed, but I think it is worth noticing that, as per https://github.com/bower/bower.json-spec#name, this name is not valid:

### name

**Required**  
Type: `String`

The name of the package as stored in the registry.

* Must be unique.
* Should be slug style for simplicity, consistency and compatibility. Example: `unicorn-cake`
* Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.
* Consecutive dashes or dots not allowed.
* 50 characters or less.

**Comment by chieffancypants** [comment]
@renato yeah -- they changed the spec after I had already published.  I suppose I can publish again under a new, more compliant name.  Thanks for the reference

**Comment by Perpherior** [comment]
actually i meet the same problem here. I'm using Ruby on Rails with rails-bower. It will raise an error 
```
/usr/local/bin/bower install -p
bower ENOTFOUND     Package chieffancypants/angular-hotkeys=chieffancypants/angular-hotkeys not found
rake aborted!
```
How can I fix it? Here is part of my bower file
```
asset "angular-scroll"
asset "chieffancypants/angular-hotkeys"

resolution "angular", "~ 1.3.2"
```

**Comment by oriko** [comment]
Hi... I think this is issue is still not fixed. 
This is what I got when trying to install:

~/g/webapp ❯❯❯ bower cache clean                                                          ⏎ master ✱
bower deleted       Cached package angular-hotkeys: /Users/orikotler/.cache/bower/packages/6fc0cf655efdb084389480c57c9d0ee8/1.7.0
~/g/webapp ❯❯❯ bower install chieffancypants/angular-hotkeys                                master ✱
bower not-cached    git://github.com/chieffancypants/angular-hotkeys.git#*
bower resolve       git://github.com/chieffancypants/angular-hotkeys.git#*
bower download      https://github.com/chieffancypants/angular-hotkeys/archive/1.7.0.tar.gz
bower not-cached    https://github.com/drahak/angular-hotkeys.git#0.2.2
bower resolve       https://github.com/drahak/angular-hotkeys.git#0.2.2
bower extract       angular-hotkeys#\* archive.tar.gz
bower resolved      git://github.com/chieffancypants/angular-hotkeys.git#1.7.0
bower ENOENT        ENOENT, mkdir '/var/folders/wl/v11qfz61035dlncqm25d_87c0000gn/T/orikotler/bower/chieffancypants/angular-hotkeys=chieffancypants/angular-hotkeys-5811-TkMwSR'

Stack trace:
Error: ENOENT, mkdir '/var/folders/wl/v11qfz61035dlncqm25d_87c0000gn/T/orikotler/bower/chieffancypants/angular-hotkeys=chieffancypants/angular-hotkeys-5811-TkMwSR'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:830:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:856:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:774:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:590:44
System info:
Bower version: 1.4.1
Node version: 0.12.2
OS: Darwin 15.0.0 x64
