### ISSUE TITLE
Input check only works for callbacks, not expressions

### ISSUE THREAD

**Issue by maxbates** [chieffancypants/angular-hotkeys#91]
In my routes, I had registered a hotkey which toggled a value on the controller's scope, e.g.

````
hotkeys : [
			['h', 'Show Intro Modal', 'showHelp = !showHelp']
		]
````

According to #17, there should not be events triggered when in an input box. However, that check has been [patched](https://github.com/chieffancypants/angular-hotkeys/blob/master/src/hotkeys.js#L63) to only check callbacks, not expressions. 

Kinda inconsistent, took me a while to figure out. At least should be better doc-ed

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look.
