### ISSUE TITLE
Only adding cfp.hotkeys as dependency breaks my tests

### ISSUE THREAD

**Issue by rajali** [chieffancypants/angular-hotkeys#92]
In my project I have added "cfp.hotkeys" as my project dependency, the keyboard shortcut is working as required but my test coverage is not able to run (even start) giving the following error:

 TypeError: 'null' is not an object (evaluating 'current.$$nextSibling')
 at E:/projects/myproject/app/vendor/angular/angular.js:12280

The test coverage starts working once I remove this dependency.

**Comment by brcarey** [comment]
@rajali until I added some shortcut keys, I had to add 
    
    .config(function (hotkeysProvider) {
        hotkeysProvider.includeCheatSheet = false;
    })

in config for my app to get my karma tests to pass

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look.
