### ISSUE TITLE
Calling Hotkeys.bindTo(scope) multiple times generates errors on RouteChange

### ISSUE THREAD

**Issue by brandonkboswell** [chieffancypants/angular-hotkeys#93]
This appears to be due to a $on destroy listener being added for every time the bindTo method is called. If I only call bindTo once and chain off of it this is not a problem. Perhaps this should be documented.

![screenshot 2014-10-03 15 34 21](https://cloud.githubusercontent.com/assets/921925/4511398/4e662502-4b34-11e4-99ac-ad973ee1c88a.png)

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If you can create a plunker to demonstrate the issue, I'm happy to re-open and take a look.
