### ISSUE TITLE
Allowing the use of external file templates or templatecached templates in addition to the current template

### ISSUE THREAD

**Issue by killyosaur** [chieffancypants/angular-hotkeys#95]
Suggestion for an enhancement is to allow for the use of template cache or an external .html template for the cheat sheet. Right now the only way to replace the cheat sheet is to rewrite it as html in code, but it is sometimes cleaner to build the template as a new file. 

You could add a templateUrl to the system and change the set for the help menu to:
         var helpMenu = this.template ? $q.when(this.template) :
            $http.get(this.templateUrl, { cache: $templateCache }).then(function (result) {
                return result.data;
            });
that will allow the switch between the two. In a variation on this file I moved the current template to a template cache angular module:
  angular.module("template/hotkeys-cheatsheet.html", []).run(["$templateCache", function ($templateCache) {
      $templateCache.put("template/hotkeys-cheatsheet.html",
        '&lt;div class="cfp-hotkeys-container fade" ng-class="{in: helpVisible}" style="display: none;"&gt;&lt;div class="cfp-hotkeys"&gt;' +
            '&lt;h4 class="cfp-hotkeys-title"&gt;{{ title }}&lt;/h4&gt;' +
            '&lt;table&gt;&lt;tbody&gt;' +
                '&lt;tr ng-repeat="hotkey in hotkeys | filter:{ description: \'!$$undefined$$\' }"&gt;' +
                    '&lt;td class="cfp-hotkeys-keys"&gt;' +
                    '&lt;span ng-repeat="key in hotkey.format() track by $index" class="cfp-hotkeys-key"&gt;{{ key }}&lt;/span&gt;' +
                    '&lt;/td&gt;' +
                    '&lt;td class="cfp-hotkeys-text"&gt;{{ hotkey.description }}&lt;/td&gt;' +
                '&lt;/tr&gt;' +
                '&lt;/tbody&gt;&lt;/table&gt;' +
                '&lt;div class="cfp-hotkeys-close" ng-click="toggleCheatSheet()"&gt;×&lt;/div&gt;' +
            '&lt;/div&gt;' +
        '&lt;/div&gt;' +
    '');
  }]);
 and included it with the main module, and set the template to default null and defaulted the new templateUrl to
     this.templateUrl = 'template/hotkeys-cheatsheet.html';

There may be a better/cleaner way to do this, I pulled this from Angular-UI's way of adding default templates and went from there.

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If this is still important to you, please create a PR.  Thanks!
