### ISSUE TITLE
Expose Moustrap.stopCallback so that we can define our own method to determine when to stop the callback.

### ISSUE THREAD

**Issue by cgallarno** [chieffancypants/angular-hotkeys#99]
Greetings,

I was wondering if it would be possible to expose a way to provide our own [stopCallback](http://craig.is/killing/mice#api.stopCallback) function, because mousetrap is triggering the hotkeys on an element inside of content editable but itself is not editable (it's a custom element).

Any help would be appreciated!

Thank You,
Cameron

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. If this is still important to you, please open a PR.  Thanks!
